/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wood_cabin.glb 
Author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wood-cabin-06fed686863447e5851e1a3250e81c5a
Title: Wood Cabin
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('./models/wood_cabin.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.061, 1.318, 0.091]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_214.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_215.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_216.geometry} material={materials.wood2} />
      </group>
      <group position={[2.358, 4.07, -1.092]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_218.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_219.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_220.geometry} material={materials.wood2} />
      </group>
      <group position={[0.261, 4.07, -1.092]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_222.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_223.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_224.geometry} material={materials.wood2} />
      </group>
      <group position={[4.711, 1.331, -1.06]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_226.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_227.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_228.geometry} material={materials.wood2} />
      </group>
      <group position={[-2.226, 1.331, -0.84]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_230.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_231.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_232.geometry} material={materials.wood2} />
      </group>
      <group position={[-3.526, 1.331, -2.198]} rotation={[0, -Math.PI / 2, 0]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_234.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_235.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_236.geometry} material={materials.wood2} />
      </group>
      <group position={[-3.526, 1.331, -4.654]} rotation={[0, -Math.PI / 2, 0]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_238.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_239.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_240.geometry} material={materials.wood2} />
      </group>
      <group position={[5.853, 1.331, -3.512]} rotation={[0, Math.PI / 2, 0]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_242.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_243.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_244.geometry} material={materials.wood2} />
      </group>
      <group position={[-3.479, 4.07, -4.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_246.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_247.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_248.geometry} material={materials.wood2} />
      </group>
      <group position={[3.567, 4.011, -4.591]} rotation={[0, Math.PI / 2, 0]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_250.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_251.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_252.geometry} material={materials.wood2} />
      </group>
      <group position={[1.908, 4.07, -6.073]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_254.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_255.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_256.geometry} material={materials.wood2} />
      </group>
      <group position={[-1.4, 4.07, -6.073]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_258.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_259.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_260.geometry} material={materials.wood2} />
      </group>
      <group position={[-0.845, 1.331, -6.144]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_262.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_263.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_264.geometry} material={materials.wood2} />
      </group>
      <group position={[3.114, 1.331, -6.144]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_266.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_267.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_268.geometry} material={materials.wood2} />
      </group>
      <group position={[-0.003, 1.034, 0.077]}>
        <mesh geometry={nodes.Object_272.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_273.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_274.geometry} material={materials.wood2} />
      </group>
      <group position={[3.566, 3.697, -2.38]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_276.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_277.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_278.geometry} material={materials.wood2} />
      </group>
      <group position={[-1.005, 4.07, -2.246]} rotation={[0, -Math.PI / 2, 0]} scale={[0.878, 1, 1.387]}>
        <mesh geometry={nodes.Object_280.geometry} material={materials.wood2} />
        <mesh geometry={nodes.Object_281.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_282.geometry} material={materials.wood2} />
      </group>
      <group position={[-6.295, -0.005, -5.161]} scale={[1.378, 1, 1.378]}>
        <mesh geometry={nodes.Object_356.geometry} material={materials['wood2.001']} />
        <mesh geometry={nodes.Object_357.geometry} material={materials.wood5} />
      </group>
      <group position={[-4.923, 0.007, -5.765]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_359.geometry} material={materials['wood1.001']} />
        <mesh geometry={nodes.Object_360.geometry} material={materials.Fabric1} />
      </group>
      <group position={[-6.19, 0.007, -6.536]}>
        <mesh geometry={nodes.Object_362.geometry} material={materials['wood1.001']} />
        <mesh geometry={nodes.Object_363.geometry} material={materials.Fabric1} />
      </group>
      <group position={[-4.923, 0.007, -4.882]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_365.geometry} material={materials['wood1.001']} />
        <mesh geometry={nodes.Object_366.geometry} material={materials.Fabric1} />
      </group>
      <group position={[-8.478, -0.091, -10.053]} scale={[0.905, 0.86, 0.905]}>
        <mesh geometry={nodes.Object_376.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_377.geometry} material={materials.pineLeave} />
      </group>
      <group position={[-4.243, -0.459, -10.226]} rotation={[0, 0.332, 0]} scale={[0.783, 0.744, 0.783]}>
        <mesh geometry={nodes.Object_379.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_380.geometry} material={materials.pineLeave} />
      </group>
      <group position={[0.295, -0.091, -11.461]} rotation={[-Math.PI, -0.613, -Math.PI]} scale={[0.905, 0.86, 0.905]}>
        <mesh geometry={nodes.Object_382.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_383.geometry} material={materials.pineLeave} />
      </group>
      <group position={[3.587, -0.091, -9.457]} rotation={[-Math.PI, 0.025, -Math.PI]} scale={[0.966, 1.091, 0.966]}>
        <mesh geometry={nodes.Object_385.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_386.geometry} material={materials.pineLeave} />
      </group>
      <group position={[7.801, -0.091, -6.526]} rotation={[0, 0.017, 0]} scale={[0.935, 1.031, 0.935]}>
        <mesh geometry={nodes.Object_388.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_389.geometry} material={materials.pineLeave} />
      </group>
      <group position={[5.924, -0.091, 2.199]} rotation={[0, -0.337, 0]} scale={[0.63, 0.598, 0.63]}>
        <mesh geometry={nodes.Object_391.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_392.geometry} material={materials.pineLeave} />
      </group>
      <group position={[6.959, -1.339, 6.45]} rotation={[0, -1.413, 0]} scale={[0.63, 0.598, 0.63]}>
        <mesh geometry={nodes.Object_394.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_395.geometry} material={materials.pineLeave} />
      </group>
      <group position={[3.983, -1.372, 5.441]} rotation={[0, 0.489, 0]} scale={[0.456, 0.433, 0.456]}>
        <mesh geometry={nodes.Object_397.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_398.geometry} material={materials.pineLeave} />
      </group>
      <group position={[-9.482, -1.372, 5.245]} rotation={[0, 0.489, 0]} scale={[0.358, 0.34, 0.358]}>
        <mesh geometry={nodes.Object_400.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_401.geometry} material={materials.pineLeave} />
      </group>
      <group position={[-6.605, -0.404, -1.063]} rotation={[0, 0.792, 0]} scale={[0.322, 0.306, 0.322]}>
        <mesh geometry={nodes.Object_403.geometry} material={materials.pineBody} />
        <mesh geometry={nodes.Object_404.geometry} material={materials.pineLeave} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.wood2} position={[-0.995, 0.936, 0.057]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.wood2} position={[3.58, 0.936, 0.055]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.wood2} position={[-1.018, 0.936, -0.838]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.wood2} position={[-3.521, 0.936, -0.852]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.wood2} position={[-3.519, 0.936, -6.127]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.wood2} position={[5.776, 0.936, -6.121]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.wood2} position={[5.776, 0.936, -1.093]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.wood2} position={[3.603, 0.936, -1.069]} scale={[0.08, 1, 0.08]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.wood2} position={[3.534, 3.655, -1.114]} scale={[0.08, 1.033, 0.08]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.wood2} position={[-0.96, 3.655, -1.114]} scale={[0.08, 1.033, 0.08]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.wood2} position={[-0.978, 3.655, -3.508]} scale={[0.08, 1.033, 0.08]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.wood2} position={[-3.454, 3.655, -3.524]} scale={[0.08, 1.033, 0.08]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.wood2} position={[-3.454, 3.655, -6.05]} scale={[0.08, 1.033, 0.08]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.wood2} position={[3.539, 3.655, -6.05]} scale={[0.08, 1.033, 0.08]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.wood2} position={[-0.026, 2.687, 0.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.wood2} position={[3.6, 2.687, -1.093]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.wood2} position={[4.812, 2.687, -1.094]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.wood2} position={[5.775, 2.687, -2.307]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.wood2} position={[4.566, 2.687, -6.123]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.wood2} position={[-3.524, 2.687, -4.913]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.wood2} position={[-2.375, 2.687, -0.84]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.wood2} position={[-0.994, 2.687, -0.653]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.wood2} position={[3.534, 5.461, -2.054]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.wood2} position={[4.566, 5.461, -6.054]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.wood2} position={[-3.455, 5.461, -4.843]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.wood2} position={[1.968, 5.461, -1.109]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.wood2} position={[-0.981, 5.461, -2.238]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.wood2} position={[-0.378, 5.461, -3.511]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 0.543, 0.085]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.wood2} position={[3.534, 2.777, -2.054]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.wood2} position={[4.566, 2.777, -6.054]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.wood2} position={[-3.455, 2.777, -4.843]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.wood2} position={[1.968, 2.777, -1.109]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.wood2} position={[-0.981, 2.777, -2.238]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.wood2} position={[-0.378, 2.777, -3.511]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 0.543, 0.085]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.wood2} position={[-0.026, 0.086, 0.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.wood2} position={[3.6, 0.086, -1.093]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.wood2} position={[4.812, 0.086, -1.094]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.wood2} position={[5.775, 0.086, -2.307]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.wood2} position={[4.566, 0.086, -6.123]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.wood2} position={[-3.524, 0.086, -4.913]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.wood2} position={[-2.375, 0.086, -0.84]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.wood2} position={[-0.994, 0.086, -0.653]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.wood2} position={[-0.026, 0.941, 0.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.wood2} position={[3.6, 0.941, -1.093]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.wood2} position={[4.812, 0.941, -1.094]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.wood2} position={[5.775, 0.941, -2.307]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.wood2} position={[4.566, 0.941, -6.123]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.wood2} position={[-3.524, 0.941, -4.913]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.wood2} position={[-2.375, 0.941, -0.84]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.wood2} position={[-0.994, 0.941, -0.653]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.wood2} position={[-0.026, 0.941, 0.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.wood2} position={[-0.026, 0.941, 0.056]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.wood2} position={[4.812, 0.941, -1.094]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.wood2} position={[5.775, 0.941, -2.307]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.wood2} position={[4.566, 0.941, -6.123]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.wood2} position={[4.566, 0.941, -6.123]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.wood2} position={[-3.524, 0.941, -4.913]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.wood2} position={[-3.524, 0.941, -4.913]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.wood2} position={[-2.375, 0.941, -0.84]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.056, 0.085]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.wood2} position={[3.652, 3.093, -1.114]} scale={[0.046, 0.339, 0.046]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.wood2} position={[5.769, 3.093, -5.291]} rotation={[0, -Math.PI / 2, 0]} scale={[0.046, 0.339, 0.046]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.wood2} position={[3.652, 3.093, -6.121]} scale={[0.046, 0.339, 0.046]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.wood2} position={[3.607, 3.705, -1.114]} scale={[0.065, 0.028, 0.065]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.wood2} position={[3.607, 2.875, -1.114]} scale={[0.065, 0.019, 0.065]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.wood2} position={[3.607, 3.543, -1.114]} scale={[0.065, 0.019, 0.065]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.wood2} position={[2.182, 5.461, -0.504]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.183, 0.085]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.wood2} position={[-4.684, 5.461, -4.968]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.334, 0.085]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.wood2} position={[2.182, 5.461, -6.642]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.091, 1.183, 0.085]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.wood2} position={[-2.983, 5.461, -3.261]} rotation={[Math.PI / 2, 0, 1.571]} scale={[0.091, 1.522, 0.085]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.wood2} position={[-1.132, 5.461, -2.21]} rotation={[Math.PI / 2, 0, 0]} scale={[0.091, 1.522, 0.085]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.wood2} position={[3.737, 5.461, -4.003]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.183, 0.085]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.wood2} position={[-2.983, 5.461, -6.289]} rotation={[Math.PI / 2, 0, 1.571]} scale={[0.091, 1.522, 0.085]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.wood2} position={[-1.132, 5.461, -4.902]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.091, 1.183, 0.085]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.bush2} position={[-4.216, -0.615, 3.558]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.877} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.bush2} position={[-4.771, -0.615, 2.9]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.877} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.bush2} position={[-3.876, -0.615, 2.847]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.244} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.bush2} position={[4.808, -1.592, 7.399]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.062} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.bush2} position={[4.847, -1.592, 6.265]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.062} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.bush2} position={[4.021, -1.592, 6.802]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.84} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.bush2} position={[-9.915, -1.649, 6.638]} rotation={[Math.PI / 2, 0, 0.141]} scale={1.556} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.bush2} position={[-8.491, -1.552, 6.24]} rotation={[Math.PI / 2, 0, 0.141]} scale={1.024} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.bush2} position={[-8.853, -1.552, 7.248]} rotation={[Math.PI / 2, 0, -1.134]} scale={1.024} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.bush2} position={[-4.261, -1.552, 6.602]} rotation={[Math.PI / 2, 0, -1.994]} scale={1.024} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.bush2} position={[-3.626, -1.552, 5.647]} rotation={[Math.PI / 2, 0, -1.994]} scale={1.024} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.bush2} position={[-2.66, -1.552, 6.632]} rotation={[Math.PI / 2, 0, -1.994]} scale={1.024} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.bush2} position={[-2.013, -1.552, 6.135]} rotation={[Math.PI / 2, 0, -1.994]} scale={1.024} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.bush2} position={[-1.286, -1.552, 6.582]} rotation={[Math.PI / 2, 0, -1.994]} scale={1.024} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.bush2} position={[-6.534, -0.787, -2.822]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.455} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.bush2} position={[-6.379, -0.766, -1.952]} rotation={[Math.PI / 2, 0, 0.666]} scale={1.014} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.bush2} position={[-7.082, -0.755, -2.132]} rotation={[Math.PI / 2, 0, -0.243]} scale={0.95} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.bush2} position={[-11.817, -0.905, -9.759]} rotation={[Math.PI / 2, 0, 0.898]} scale={2.611} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.bush2} position={[-10.135, -0.96, -8.714]} rotation={[Math.PI / 2, 0, 0.243]} scale={1.957} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.bush2} position={[-11.601, -0.885, -8.039]} rotation={[Math.PI / 2, 0, -0.26]} scale={1.439} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.bush2} position={[-11.338, -0.796, -4.181]} rotation={[Math.PI / 2, 0, -0.635]} scale={1.556} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.bush2} position={[-12.168, -0.944, -3.448]} rotation={[Math.PI / 2, 0, -0.635]} scale={0.969} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.bush2} position={[-11.282, -0.944, -3.269]} rotation={[Math.PI / 2, 0, -0.635]} scale={1.17} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.bush2} position={[7.277, -0.641, -0.926]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={2.273} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.bush2} position={[6.058, -0.641, 0.328]} rotation={[Math.PI / 2, 0, 1.006]} scale={1.902} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.bush2} position={[7.516, -0.726, 0.626]} rotation={[Math.PI / 2, 0, 1.985]} scale={1.821} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.bush2} position={[4.576, -0.726, 3.808]} rotation={[Math.PI / 2, 0, 1.985]} scale={1.82} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.bush2} position={[3.683, -0.726, 2.982]} rotation={[Math.PI / 2, 0, 1.047]} scale={1.254} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.bush2} position={[3.683, -0.713, 3.968]} rotation={[Math.PI / 2, 0, 1.047]} scale={1.054} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.bush2} position={[-2.105, -0.687, -10.093]} rotation={[Math.PI / 2, 0, 0.898]} scale={1.883} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.bush2} position={[-1.07, -0.687, -9.569]} rotation={[Math.PI / 2, 0, 0.158]} scale={1.081} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.wood2} position={[0, 1, 0.137]} />
      <mesh geometry={nodes.Object_270.geometry} material={materials.wood2} position={[3.61, 3.697, -2.38]} rotation={[0, Math.PI / 2, 0]} scale={[0.55, 1.05, 0.025]} />
      <mesh geometry={nodes.Object_284.geometry} material={materials.wood1} position={[-10.016, -0.739, 1.132]} />
      <mesh geometry={nodes.Object_286.geometry} material={materials.wood3} position={[1.985, -1, -2.895]} scale={[4.519, 1, 4.519]} />
      <mesh geometry={nodes.Object_288.geometry} material={materials.wood1} position={[-2.561, -0.791, -1.12]} scale={11.014} />
      <mesh geometry={nodes.Object_290.geometry} material={materials.wood1} position={[-2.561, -0.791, -1.12]} scale={11.014} />
      <mesh geometry={nodes.Object_292.geometry} material={materials.material_0} position={[-2.561, -0.791, -1.12]} scale={11.014} />
      <mesh geometry={nodes.Object_294.geometry} material={materials.Snow} position={[-11.713, -1.146, 5.177]} />
      <mesh geometry={nodes.Object_296.geometry} material={materials.wood3} position={[0, 1.265, 0]} scale={[1, 1.273, 1]} />
      <mesh geometry={nodes.Object_298.geometry} material={materials.grass} position={[1.253, -0.618, 3.864]} scale={1.01} />
      <mesh geometry={nodes.Object_300.geometry} material={materials.grass} position={[-6.164, -1.469, 4.902]} scale={1.01} />
      <mesh geometry={nodes.Object_302.geometry} material={materials.grass} position={[-6.691, -1.469, 5.004]} rotation={[0, 0.581, 0]} scale={1.01} />
      <mesh geometry={nodes.Object_304.geometry} material={materials.grass} position={[-6.389, -1.469, 5.52]} rotation={[0, 0.581, 0]} scale={0.871} />
      <mesh geometry={nodes.Object_306.geometry} material={materials.grass} position={[-7.024, -1.469, 5.478]} scale={1.01} />
      <mesh geometry={nodes.Object_308.geometry} material={materials.grass} position={[-7.551, -1.469, 5.579]} rotation={[0, 0.581, 0]} scale={1.01} />
      <mesh geometry={nodes.Object_310.geometry} material={materials.grass} position={[-7.249, -1.469, 6.096]} rotation={[0, 0.581, 0]} scale={0.871} />
      <mesh geometry={nodes.Object_312.geometry} material={materials.grass} position={[-9.797, -1.496, 7.382]} scale={0.864} />
      <mesh geometry={nodes.Object_314.geometry} material={materials.grass} position={[-10.249, -1.557, 7.469]} rotation={[0, 0.157, 0]} scale={0.711} />
      <mesh geometry={nodes.Object_316.geometry} material={materials.grass} position={[-9.99, -1.496, 7.912]} rotation={[-Math.PI, 1.553, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_318.geometry} material={materials.grass} position={[-4.925, -1.496, 6.526]} rotation={[0, 0.478, 0]} scale={0.864} />
      <mesh geometry={nodes.Object_320.geometry} material={materials.grass} position={[-5.285, -1.557, 6.811]} rotation={[0, 0.635, 0]} scale={0.711} />
      <mesh geometry={nodes.Object_322.geometry} material={materials.grass} position={[-4.853, -1.496, 7.085]} rotation={[-Math.PI, 1.075, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_324.geometry} material={materials.grass} position={[-1.652, -1.496, 5.483]} rotation={[-Math.PI, 1.055, -Math.PI]} scale={0.864} />
      <mesh geometry={nodes.Object_326.geometry} material={materials.grass} position={[-1.354, -1.557, 5.833]} rotation={[-Math.PI, 0.898, -Math.PI]} scale={0.711} />
      <mesh geometry={nodes.Object_328.geometry} material={materials.grass} position={[-1.096, -1.496, 5.39]} rotation={[-Math.PI, -0.533, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_330.geometry} material={materials.grass} position={[-1.694, -1.496, 7.103]} rotation={[-Math.PI, 1.394, -Math.PI]} scale={0.864} />
      <mesh geometry={nodes.Object_332.geometry} material={materials.grass} position={[-1.529, -1.557, 7.532]} rotation={[-Math.PI, 1.238, -Math.PI]} scale={0.711} />
      <mesh geometry={nodes.Object_334.geometry} material={materials.grass} position={[-1.139, -1.496, 7.2]} rotation={[-Math.PI, -0.194, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_336.geometry} material={materials.grass} position={[3.404, -1.496, 7.041]} rotation={[0, 1.502, 0]} scale={0.864} />
      <mesh geometry={nodes.Object_338.geometry} material={materials.grass} position={[3.46, -1.557, 7.497]} rotation={[-Math.PI, 1.483, -Math.PI]} scale={0.711} />
      <mesh geometry={nodes.Object_340.geometry} material={materials.grass} position={[3.919, -1.496, 7.269]} rotation={[-Math.PI, 0.052, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_342.geometry} material={materials.grass} position={[-12.07, -0.581, -2.515]} rotation={[-Math.PI, 1.553, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_344.geometry} material={materials.grass} position={[-10.608, -0.581, -7.508]} rotation={[-Math.PI, 1.553, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_346.geometry} material={materials.grass} position={[-12.552, -0.581, -8.364]} rotation={[-Math.PI, 1.553, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_348.geometry} material={materials.grass} position={[-13.108, -0.581, 3.68]} rotation={[-Math.PI, 0.924, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_350.geometry} material={materials.grass} position={[-6.666, -0.581, -1.026]} rotation={[-Math.PI, 0.576, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_352.geometry} material={materials.grass} position={[-6.833, -0.581, -1.448]} rotation={[-Math.PI, 0.576, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_354.geometry} material={materials.grass} position={[-7.463, -0.581, -3.037]} rotation={[-Math.PI, 0.576, -Math.PI]} scale={0.746} />
      <mesh geometry={nodes.Object_368.geometry} material={materials.woodb} position={[2.585, 2.954, 0.056]} scale={[1, 0.269, 1]} />
      <mesh geometry={nodes.Object_370.geometry} material={materials.Snow} position={[-0.173, 5.919, -3.371]} />
      <mesh geometry={nodes.Object_372.geometry} material={materials.Snow} position={[-2.549, -0.99, -1.649]} />
      <mesh geometry={nodes.Object_374.geometry} material={materials.snows} position={[-15.169, -1.978, -6.673]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Object_406.geometry} material={materials.wood1} position={[1.302, 2.528, 0.065]} rotation={[-0.19, 0, 0]} />
      <mesh geometry={nodes.Object_408.geometry} material={materials.wood1} position={[-1.004, 2.528, -0.408]} rotation={[-Math.PI / 2, -1.38, -Math.PI / 2]} scale={[0.406, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_410.geometry} material={materials.wood1} position={[-2.208, 2.528, -0.848]} rotation={[-0.19, 0, 0]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_412.geometry} material={materials.wood1} position={[-3.521, 2.528, -2.168]} rotation={[-Math.PI / 2, -1.38, -Math.PI / 2]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_414.geometry} material={materials.wood1} position={[-2.207, 2.528, -6.133]} rotation={[-2.951, 0, Math.PI]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_416.geometry} material={materials.wood1} position={[5.789, 2.528, -4.813]} rotation={[-1.571, 1.38, 1.571]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_418.geometry} material={materials.wood1} position={[4.468, 2.528, -1.083]} rotation={[-0.19, 0, 0]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_420.geometry} material={materials.wood1} position={[3.588, 2.528, 0.12]} rotation={[-1.571, 1.38, 1.571]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_422.geometry} material={materials.wood1} position={[1.309, 5.279, -1.103]} rotation={[-0.19, 0, 0]} scale={[2.173, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_424.geometry} material={materials.wood1} position={[-2.165, 5.279, -3.516]} rotation={[-0.19, 0, 0]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_426.geometry} material={materials.wood1} position={[-3.469, 5.279, -2.095]} rotation={[-Math.PI / 2, -1.38, -Math.PI / 2]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_428.geometry} material={materials.wood1} position={[-2.128, 5.279, -6.06]} rotation={[-2.951, 0, Math.PI]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_430.geometry} material={materials.wood1} position={[3.545, 5.279, -4.813]} rotation={[-1.571, 1.38, 1.571]} scale={[1.258, 0.148, 0.028]} />
      <mesh geometry={nodes.Object_432.geometry} material={materials.wood1} position={[-0.964, 5.279, 0.089]} rotation={[-Math.PI / 2, -1.38, -Math.PI / 2]} scale={[1.258, 0.148, 0.028]} />
    </group>
  )
}

useGLTF.preload('./models/wood_cabin.glb')
